language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- linux

before_install:
- echo $LANG
- echo $LC_ALL
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y make automake autotools-dev  libboost1.58-dev libboost-dev libboost-all-dev libssl-dev libbz2-dev
branches:
  only:
  - mqfDevelopmenet
